### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Aashish792** [GrayXu/Virtual-Try-On-Flask#8]
Error on running: python3 main.py

WARNING:tensorflow:From /Users/aashish/Desktop/Virtual-Try-On-Flask/JPPNet.py:25: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

/Users/aashish/Desktop/Virtual-Try-On-Flask/JPPNet.py:26: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  graph_def.ParseFromString(f.read())
WARNING:tensorflow:From /Users/aashish/Desktop/Virtual-Try-On-Flask/JPPNet.py:29: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Traceback (most recent call last):
  File "main.py", line 42, in <module>
    "checkpoints/tom.pth")
  File "/Users/aashish/Desktop/Virtual-Try-On-Flask/Model.py", line 33, in __init__
    self.jpp = JPP(pb_path)
  File "/Users/aashish/Desktop/Virtual-Try-On-Flask/JPPNet.py", line 30, in __init__
    self.img_tensor = sess.graph.get_tensor_by_name('img_1:0')
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3783, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3649, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'img_1:0' refers to a Tensor which does not exist. The operation, 'img_1', does not exist in the graph."

**Comment by Aashish792** [comment]
<img width="1325" alt="Screen Shot 2020-05-08 at 2 19 19 PM" src="https://user-images.githubusercontent.com/37804913/81387866-2187d400-9137-11ea-8289-dbbd6a2ad31a.png">

How to solve this error any help
